name: Pull Requests title rules

on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize
      - reopened
    branches:
      - main
      - dev

jobs:
  check-pr-tittle:
    uses: bigboxrepo/pipelineshub/.github/workflows/ci-pr-titles-check-workflow.yaml@main
    secrets:
      WORKFLOW_TOKEN: ${{ secrets.WORKFLOW_TOKEN }}
